BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `user` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL,
	`email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `token` (
	`userId`	INTEGER,
	`token`	TEXT
);
CREATE TABLE IF NOT EXISTS `post` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	text NOT NULL,
	`body`	text NOT NULL,
	`userId`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `comment` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`body`	text NOT NULL,
	`postId`	INTEGER NOT NULL,
	`userId`	INTEGER NOT NULL
);
COMMIT;
